version: '2.0'
services:

  parts:
    container_name: parts
    image: parts
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    volumes:
      - /Users/mwilken/source/tutorials/parts/images:/opt/images
    environment:
      - "SPRING_PROFILES_ACTIVE=h2,credentials"
