spring:
  datasource:
    hikari:
      connection-test-query: select 1
      maximum-pool-size: 5
      minimum-idle: 300000
    password:
    username: sa
    #    url: jdbc:h2:tcp://localhost/~/.h2/parts;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:mem:parts;DB_CLOSE_DELAY=-1
  flyway:
    baseline-on-migrate: true
    checkLocation: true
    enabled: true
    out-of-order: true
    locations: classpath:/db/migration/h2
    schemas: PUBLIC
    validate-on-migrate: true
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        show_sql: false
  h2:
    console:
      enabled: true
      path: /h2
