insert into PART(ID, NAME, COST, QUANTITY, SHORT_DESCRIPTION, DESCRIPTION, URL)
values (NEXTVAL('part_id_seq'), '5V 1 Channel Relay Module', 2.27, 3,
        '5V Indicator Light LED One 1 Channel Relay Module For Arduino ARM PIC AVR DSP',
        'Brand new and high quality. The 8550 transistor drive, drive ability.\n High quality 5v relay. Have relay status indicator led.\n Relay control interface by single chip IO. Low level suction close, high level release.\n Easy to use, simple 3 line structure. Power LED(Green), relay status indicator LED(Red).\n Size: 4.4cm x 2.6cm - 1.7inch x 1inch.',
        'https://www.amazon.com/gp/product/B00P7QDJD2/ref=od_aui_detailpages00?ie=UTF8&psc=1'),
       (NEXTVAL('part_id_seq'), 'Solderless BreadBoard',
        2.10, 4,
        'BB400 Solderless Plug-in BreadBoard, 400 tie-points, 4 power rails, 3.3 x 2.2 x 0.3in (84 x 55 x 9mm)',
        '400 tie points total: 300 tie-point IC-circuit area plus two 50 tie-point distribution strips providing 4 power rails.\n White ABS plastic body with black printed legend. Color legend on distribution strips.\n Contacts are Phosphor Bronze with Plated Nickel Finish, rated for 50,000 insertions. Rated at 36 Volts, 2 Amps.\n Insertion Wire Size is 21 to 26 AWG, 0.016 to 0.028 inches diameter (0.4 to 0.7mm diameter)\nSize: 3.3 x 2.1 x 0.3in (84 x 54.3 x 8.5mm). Peelable adhesive tape backing provided for attaching to a surface.',
        'https://www.amazon.com/gp/product/B0040Z1ERO/ref=od_aui_detailpages00?ie=UTF8&psc=1'),
       (NEXTVAL('part_id_seq'), 'OpenSprinkler',
        77.99, 1,
        'OpenSprinkler Pi (OSPi)',
        'OpenSprinkler Pi (OSPi) is a sprinkler / irrigation extension board for Raspberry Pi (RPi). It allows RPi to directly access and control sprinkler valves. This is version 1.4 with OpenSprinkler injection molded enclosure. The built-in components include on-board 24V AC to 5V DC switching regulator, solenoid drivers, DS1307 RTC and battery, PCF8591T 8-bit A/D D/A converter (4 input and 1 output channels), fuse, rain sensor terminal, one general-purpose relay, and per-station transient voltage suppressor (bidirectional TVS).',
        'http://rayshobby.net/cart/ospi'),
       (NEXTVAL('part_id_seq'), 'Distance Measuring Transducer',
        .99, 1,
        'Ultrasonic Module HC-SR04 Distance Measuring Transducer Sensor For Arduino',
        'Module main technical parameters:\n1.Working Voltage : 5V(DC)\n2.Static current: Less than 2mA.\n 3.Output signal: Electric frequency signal, High Level 5V, Low Level 0V.\n 4.Input trigger Signal: 10us TTL impulse\n5.Echo Signal : output TTL PWL Signal\n6. Trigger Pulse Input\n7. Echo Pulse Output\nUse method:\nSupply module with 5V, the output will be 5V while obstacle in range, or 0V if not.The out pin of this module is used as a switching output when anti-theft module, and without the feet when ranging modules.\n Note : the module should be inserted in the circuit before been power, which avoid producing high level of misoperation;if not, then power again.\n Module Working Principle:\n1.Adopt IO trigger through supplying at least 10us sequence of high level signal.\n 2.The module automatically send eight 40khz square wave and automatically detect whether receive the returning pulse signal.\n 3.If there is signals returning, through outputting high level and the time of high level continuing is the time of that from the ultrasonic transmitting to receiving. Test distance = (high level time * sound velocity (340M/S) / 2.\n \note : This module is not suitable to connect with electric power, if you need to connect this module with electronic power,then let the GND terminal of this module to be connected first,otherwise, it will Affect the Normal work of the Module',
        'http://www.ebay.com/itm/272274225943'),
       (NEXTVAL('part_id_seq'), 'Micro USB OTG Adapter',
        4.99, 3,
        'Micro USB OTG Adapter, LDesign Micro USB to USB Flash Drive OTG Adapter',
        'OTG USB Flash Drive: Plug in your USB flash drive to make it OTG enabled, allowing your phone to read and write data\nPhone to Phone Changing: Allow you to charge a phone via another Android phone\nConnect the OTG adapter with mouse or keyboard, allowing you to play games or view files or write messages by the phone\nCompatible with all USB flash drives, smart phones/tablet PC with OTG function and Micro USB port\nMini size OTG adapter with storage box, lightweight, portable and simple to use',
        'http://www.ebay.com/itm/Micro-USB-OTG-Adapter-LDesign-Micro-USB-to-USB-Flash-Drive-OTG-Adapter-for-An-/201681549715?hash=item2ef5283993:g:V~4AAOSwI2xX8VmL'),
       (NEXTVAL('part_id_seq'), 'ESP8266 Breadboard Adapter',
        3.84, 1,
        'Addicore nRF24L01+ and ESP8266 Breadboard Adapter (BB-ADTR)',
        'The BB-ADTR breadboard adapter makes it easy to connect any 2x4 pin device or module, such as the nRF24L01+ or ESP8266 ESP-01 modules, to a standard breadboard. The adapter has a wide enough footprint to secure the board and a connected module firmly to a breadboard, but is small enough to conserve breadboard real estate. Made of a quality 1.6mm thick FR4 industrial quality PCB board with the pads pre-tinned with a lead free HASL finish we made sure this little board would be durable and easy to solder. \n\nAdapter comes unassembled, requires soldering.',
        'http://www.ebay.com/itm/172129793114'),
       (NEXTVAL('part_id_seq'), 'Temperature and Humidity Sensor',
        2.57, 1,
        'Temperature and Humidity Digital Arduino Module or Raspberry Pi Sensor DHT11',
        '1* DHT11 sensor module\n\nDHT11 Digital Temperature and Humidity Sensor Module for Raspberry Pi & Arduino\n\nAOSONG is one of the biggest companies which specialized in senor in China.\n \n.DHT series numeric humiture sensor.\n \n.Humidity measuring range: 20％～90%RH(0－50℃temperature compensation).\n \n.Temperature measuring range: 0～+50℃.\n \n.Humidity measurement accuracy: ±5.0%RH.\n \n.Temperature measurement accuracy: ±2.0℃.\n \n.response time: <5s.\n \n.low power consumption.\n \n.Size:2.3cm x 1.2cm x 0.5cm.',
        'http://www.ebay.com/itm/262568039299'),
       (NEXTVAL('part_id_seq'), 'Power Supply Module',
        .99, 1,
        'MB102 Breadboard Power Supply Module 3.3V 5V For Arduino Solderless Breadboard',
        '1.Brand new and high quality.\n 2.Breadboard power supply module, compatible with 5 V, 3.3 V\nApply to MB102 breadboard\n3.Input voltage: 6.5-12 V (DC) or USB power supply\n4.Output voltage: 3.3V/5V can switch over\n5.Maximum output current: <700 ma\n6.Fluctuation two road independent control, can switch over to 0 V, 3.3 V, 5 V\n7.On-board two groups of 3.3V, 5V DC output plug pin, convenient external lead use.\n 8.Size:5.3cm x 3.5cm',
        'https://www.ebay.com/itm/MB102-Breadboard-Power-Supply-Module-3-3V-5V-For-Arduino-Solderless-Breadboard/252572234136?epid=19020125558&hash=item3ace7a7198:g:AxEAAOSw9N1Vk75H:rk:7:pf:0'),
       (NEXTVAL('part_id_seq'), 'ESP8266 ESP-01 Board',
        2.80, 1,
        'ESP8266 ESP-01 Programming and Development Tool Board (Auto-reset)',
        'PART NO. BB-E01ADP\nVR Power Input: 5V ~ 16V.\n 3.3V Power Output Current Up to 350mA.\n Automatically selects the power from VR or VUSB.\n Breadboard Friendly and FTDI Basic 5V Interface.\n It can be used in the BB-E01 or China ESP-01 blue board(old) / black board(new).\n Built-in Auto-reset Function, Suitable for use in the Arduino IDE. FLASH DOWNLOAD TOOLS and any Terminal Software.\n Hold Down the "Download Button" before Downloading the Program, Release the Button after Entering the Download Process. (So Easy!)\nBoard Size: 23 x 15 mm, 2x5 Socket only 5mm height.\n Pin to Pin Pitch: 2.54 mm / 0.1 in.',
        'http://www.ebay.com/itm/111819907565'),
       (NEXTVAL('part_id_seq'), 'Step-Down Power Supply Buck Module',
        2.09, 3,
        '2A DC 5V-23V to 3.3V DC-DC Step-Down Power Supply Buck Module for esp8266 WiFi',
        'Input voltage 4.75~23V,output 3.3V\nLong time maximum output current 1.3A(5V to 3.3V)\nShort time maximum output current 2A(5V to 3.3V)\nDC-DC Step-Down Converter module working frequency 1.4MHz. efficiency is 78-91% .\n 2.54mm pin pitch, Arduino Breadboard MCU Development Board friendly\nExcluding Pin Size 22.5mm x 13.5mm x 6.5mm(small)\nWeight : about 2.2g(Very light)"Download Button" before Downloading the Program, Release the Button after Entering the Download Process. (So Easy!)\nBoard Size: 23 x 15 mm, 2x5 Socket only 5mm height.\n Pin to Pin Pitch: 2.54 mm / 0.1 in.',
        'http://www.ebay.com/itm/281667714648'),
       (NEXTVAL('part_id_seq'), 'Mini HDMI to HDMI Male to Female Adapter',
        5.99, 1,
        'Cable Matters Gold Plated Mini HDMI to HDMI Male to Female Adapter',
        'The Mini HDMI adapter adapts an HDMI cable to fit into a Mini HDMI port on a laptop, camcorder, camera, or tablet\nFully compliant with the latest HDMI standard, this Mini HDMI to HDMI adapter is capable of carrying the increased bandwidth of HDMI 2.0 at 18 Gbps\nSupports Audio Return Channel (ARC), HDMI Ethernet Channel (HEC), 48 Bit Deep Color, 32 channel audio, HDCP, Dolby True HD 7.1 audio, and 3D video\nSupports resolutions up to 4Kx2K (UHD) including 4096x2160, 3840x2160, 2560x1600, 2560x1440, 1920x1200, and 1080p\nGold plated male to female adapter resists corrosion and provides rigidity. Grip treads help easy plugging and unplugging"Download Button" before Downloading the Program, Release the Button after Entering the Download Process. (So Easy!)\nBoard Size: 23 x 15 mm, 2x5 Socket only 5mm height.\n Pin to Pin Pitch: 2.54 mm / 0.1 in.',
        'https://www.amazon.com/gp/your-account/order-history/ref=oh_aui_menu_yo_new_digital?ie=UTF8&digitalOrders=1&orderFilter=months-6&unifiedOrders=0'),
       (NEXTVAL('part_id_seq'), 'Edimax EW-7811Un 150Mbps 11n Wi-Fi USB Adapter',
        8.99, 3,
        'Edimax EW-7811Un 150Mbps 11n Wi-Fi USB Adapter',
        'Supports 150 Mbps 802.11n Wireless data rate - the latest wireless standard. Permits users to have the farthest range with the widest coverage. (Up to 6 times the speed and 3 times the coverage of 802.11b.)."Download Button" before Downloading the Program, Release the Button after Entering the Download Process. (So Easy!)\nBoard Size: 23 x 15 mm, 2x5 Socket only 5mm height.\n Pin to Pin Pitch: 2.54 mm / 0.1 in.',
        'https://www.amazon.com/gp/product/B003MTTJOY/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1'),
       (NEXTVAL('part_id_seq'), 'SE MZ101B Helping Hand with Magnifying Glass',
        6.75, 1,
        'SE MZ101B Helping Hand with Magnifying Glass',
        'Built-in magnifying glass (4x) aids in minute detail work\n2 Alligator clips on 4-way swivels-holds items securely (leaving hands free)"Download Button" before Downloading the Program, Release the Button after Entering the Download Process. (So Easy!)\nBoard Size: 23 x 15 mm, 2x5 Socket only 5mm height.\n Pin to Pin Pitch: 2.54 mm / 0.1 in.',
        'https://www.amazon.com/gp/product/B000RB38X8/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1'),
       (NEXTVAL('part_id_seq'), 'Double sided perf board PCB',
        4.49, 1,
        'Double sided perf board PCB',
        '2x8cm - 3 pcs\n6 holes wide, 28 holes long',
        'http://www.ebay.com/itm/322229292047'),
       (NEXTVAL('part_id_seq'), '2 Channel Logic Level Converter',
        1.03, 1,
        '2 Channel Logic Level Converter 3.3V to 5V TTL Bi-directional Module',
        '2-channel high-voltage and low-voltage logic logic bidirectional translation\n2-channel high-voltage logic low voltage logic converted into a one-way conversion\nModule compatible with bread plate, can be used directly put on the bread board\nInstructions for use: high voltage is 5V low voltage of 3.3V for example:\nHV and 5V power connection\nLV with 3.3V power supply connection\nGND connection negative power, two power commons\nRXI input 5v TTL, in RXO 3.3v TTL output\nTXI input and output 3.3V TTL, TXO input and output 5V TTL, TXI and TXO bi Huzhuan',
        'http://www.ebay.com/itm/381351795284'),
       (NEXTVAL('part_id_seq'), 'Resistors Assortment',
        9.99, 1,
        'Resistors Assortment',
        '25 pcs each of the following standard values: 10, 22, 47, 100, 150, 220, 270, 330, 470, 510, 680, 1k, 2k, 2.2k, 3.3k, 4.7k, 5.1k, 6.8k, 10k, 22k, 47k, 51k, 68k, 100k, 220k, 300k, 470k, 680k and 1M\nYou dont need to read color bands,
        Each value is individually labeled and packaged\n1% tolerance, 1 / 4 Watt,
        Metal film resistors\nQuantity: 750 pcs (30 Values x 25 pcs).\n Lead free and RoHS Compliant,
        1 / 2w asin:B018NEJYU6;
1w asin:B01DKC9C1C',
        'https://www.amazon.com/gp/product/B016NXK6QK/ref=oh_aui_detailpage_o04_s00?ie=UTF8&psc=1'),
       (NEXTVAL('part_id_seq'), 'PNP Silicon Transistor',
        6.47, 1,
        'PNP Silicon Transistor S8550',
        'Product Name : PNP Silicon Transistor;Quantity : 50+/-2% Pcs;Model : S8550\nPackage : TO-92;Collector Base Voltage : 30V\nCollector Current : 700mA;Collector Dissipation : 1W\nTerminal Size : 14 x 1mm/ 0.55\" x 0.039\" ( L* Pitch);Body Dimension : 18 x 4 x 3mm/ 0.7\" x 0.16\" x 0.12\" (L*W*T)\nWeight : 10g;Package Content : 50 x Silicon PNP Transistor',
        'https://www.amazon.com/gp/product/B008IFYFFA/ref=oh_aui_detailpage_o04_s00?ie=UTF8&psc=1'),
       (NEXTVAL('part_id_seq'), 'NPN Silicon Transistor 2N2222',
        6.13, 1,
        'NPN Silicon Transistor 2N2222',
        '2N2222 NPN TO-92 Plastic-Encapsulate Power Transistors 75V 600mA',
        'https://www.amazon.com/gp/product/B00R1M3DA4/ref=oh_aui_detailpage_o04_s00?ie=UTF8&psc=1'),
       (NEXTVAL('part_id_seq'), 'OLED LCD',
        13.95, 1,
        'ACROBOTIC 0.96 Inches Yellow-Blue I2C 128x64 OLED LCD',
        'Operating Voltage: 3.3~5VDC\nConnects via I2C to any microcontroller or single-board computer\nWorks with ESP8266, Arduino, 8051, MSP420, STM32, Raspberry Pi!\n Pixel Color: yellow (16 rows) and blue. Resolution: 128x64 pixels; Size: 0.96in (diagonal)\nBuilt-in SSD1306 driver; I2C address: 0x3C',
        'https://www.amazon.com/gp/product/B01AE3MR7Q/ref=oh_aui_detailpage_o04_s00?ie=UTF8&psc=1'),
       (NEXTVAL('part_id_seq'), '10K ohm Potentiometers',
        5.54, 1,
        '10 Pcs 10K ohm 3 Pins 6mm Split Shaft Rotary Linear Taper Potentiometers w Knob',
        'Features: 10K ohm, 3 Terminals, Single Linear (Type B), control Knobs.\n Top adjustment type and knurled shaft for easy operate in daily use time.\n Main used to control electrical devices such as volume controls on audio equipment.\n Knurled shaft with split design for push-on knob.',
        'https://www.amazon.com/gp/product/B00DN7MSXY/ref=od_aui_detailpages00?ie=UTF8&psc=1'),
       (NEXTVAL('part_id_seq'), 'Magnetic Reed Switch sensor',
        1.99, 1,
        'Window or Door Contact Magnetic Reed Switch Alarm security electric sensor',
        'The reed switch is an electrical switch operated by an applied magnetic field. It was invented at Bell Telephone Laboratories in 1936 by W. B. Ellwood. It consists of a pair of contacts on ferrous metal reeds in a hermetically sealed glass envelope. There are two types of reed switches: "normally open" reed switches and "normally closed" reed switches. The metal reeds on a normally open switch stay open when there is no magnet near the switch. In the presence of a magnetic field, the contacts of a normally-open reed switch will close. A normally-closed reed switch is closed when it is not near a magnet; as a magnet is brought close to it, a normally-closed switch will open.',
        'http://www.ebay.com/itm/331761448987'),
       (NEXTVAL('part_id_seq'), '5 pcs Double Row Female Pin Header',
        3.79, 1,
        '5 pcs 2x20 Pin 2.54 mm Double Row Female Pin Header',
        'Specification\nConnector Type Female Header\nPin Type Straight\nNumber of Pin 40 ( 2 x 20 )\nNumber of Row Double\nPitch 2.54mm\nGender Female',
        'http://www.ebay.com/itm/321751750272'),
       (NEXTVAL('part_id_seq'), '20Pcs Single Row Right Angle Pin Header',
        1.99, 1,
        '20Pcs 40Pin 2.54mm Single Row Right Angle Pin Header Strip Arduino kit',
        '20PCS * 40 Pin 2.54mm Right Angle Single Row Pin Header PCB For Arduino',
        'http://www.ebay.com/itm/400825759103'),
       (NEXTVAL('part_id_seq'), 'Solar Panel Module System',
        4.67, 1,
        'Solar Panel Module System',
        'Type: DIY Solar Panel, Other Camping Gear \nMaterial: Polycrystalline silicon, Electronic Components\nPower& Voltage: 0.12w-3.5w,1.5v-18v\nCurrent (mA): 60-580',
        'http://www.ebay.com/itm/112008109654'),
       (NEXTVAL('part_id_seq'), 'Camera Module Board 5MP Webcam Video 1080p 720p',
        11.38, 1,
        'Camera Module Board 5MP Webcam Video 1080p 720p',
        'Fully Compatible with Raspberry Pi A/B/B+/2/3\n \n5MP Omnivision 5647 Camera Module\n \nStill Picture Resolution: 2592 x 1944\n \nVideo: Supports 1080p @ 30fps, 720p @ 60fps  and 640x480p 60/90 Recording\n \n15-pin MIPI Camera Serial Interface - Plugs Directly into the Raspberry Pi Board\n \nSize: 20 x 25 x 9mm',
        'http://www.ebay.com/itm/381181830171'),
       (NEXTVAL('part_id_seq'), '5pcs Plastic Battery Holder Storage Box',
        1.83, 1,
        '5pcs Plastic Battery Holder Storage Box Case for 1x 18650 Rechargeable Battery',
        '- High Quality Plastic Holder.\n  - Small size, easy to carry.\n  - 1pcs 18650 Battery Holder Case Leads 3.7V  Clip Type for Soldering / Connecting.\n  - Takes 1 standard size 18650 batteries side by side to form a compact battery of 3.7V using alkaline batteries.\n  - Batteries Not Included.',
        'http://www.ebay.com/itm/361262848840'),
       (NEXTVAL('part_id_seq'), '2pcs Rechargeable Li-ion Battery',
        2.92, 1,
        '2pcs Rechargeable Li-ion Battery Blue',
        '2pcs 18650 4200mAh 3.7V Rechargeable Li-ion Battery Blue',
        'http://www.ebay.com/itm/2pcs-18650-4200mAh-3-7V-Rechargeable-Li-ion-Battery-Blue-for-Flashlight-CP/331952683016?_trksid=p2054502.c100227.m3827&_trkparms=aid%3D111001%26algo%3DREC.SEED%26ao%3D1%26asc%3D39352%26meid%3D7b44f4d1b4f043aab875d086578da963%26pid%3D100227%26rk%3D1%26rkt%3D14%26sd%3D331952683016'),
       (NEXTVAL('part_id_seq'), 'Regulated Switching Power Supply',
        4.39, 1,
        'S-10-5 5V 2A Regulated Switching Power Supply - Silver (110~220V)',
        'This is a DC 5V power supply unit for professional use on security surveillance system, CCTV security camera, IP camera, etc. Safety design with shortage protection, overload protection and auto voltage switching. This is a perfect choice to use as a LED Driver for LED lighting without flickering light & ensue the life span of your LED. Current output is possible for LED lighting with dimmable function. \n\n- Color: Silver\n- Iron housing\n- Input: AC 110~220V\n- Output: 5V/2A\n- Great switching power supply for home appliances',
        'http://www.dx.com/p/5v-2a-regulated-switching-power-supply-110-220v-94518#.V_EKbDKZNZo'),
       (NEXTVAL('part_id_seq'), '10PCS Micro USB Male Plug Connectors',
        .99, 1,
        '10PCS DIY Micro USB Male Plug Connectors Kit w/ Covers Black ME',
        '0.71 in x 0.39 in x 0.28 in (1.8 cm x 1 cm x 0.7 cm)',
        'http://www.ebay.com/itm/152197938751'),
       (NEXTVAL('part_id_seq'), 'Buck Step-down Power Converter',
        1.98, 1,
        'LM2596 Buck Step-down Power Converter Module DC 4.0~40 to 1.3-37V LED Voltmeter',
        'Input voltage range:4~40VDC\nOutput voltage range:1.25-37VDC adjustable\nOutput current:2A\nvoltmeter range: 0 to 0V, error +- 0.1V',
        'http://www.ebay.com/itm/LM2596-Buck-Step-down-Power-Converter-Module-DC-4-0-40-to-1-3-37V-LED-Voltmeter-/400802470941?hash=item5d51b05c1d:g:XccAAOSwYSlXhIFg'),
       (NEXTVAL('part_id_seq'), 'FTDI USB to TTL Serial Adapter',
        1.89, 1,
        'FT232RL 3.3V 5.5V FTDI USB to TTL Serial Adapter Module for Arduino Mini Port',
        'Chip: FT232RL\nUSB supply power, can choose 5V or 3.3V interface level\nPC size: 17mm x 32.5mm\nElicit all signal port of FT232RL chip, TTL/CMOS level\nRXD/TXD transceiver communicastion signals indicator light',
        'http://www.ebay.com/itm/162008634869'),
       (NEXTVAL('part_id_seq'), 'ESP8266 ESP-01',
        2.01, 3,
        '1PCS ESP8266 ESP-01 WIFI Wireless Transceiver Send Receive LWIP AP+STA',
        'This module requiers a 3.3V supply for VCC, and 3.3V logic. It is not 5V tolerant! Connecting RX and TX on a 5V Arduino will destroy this module. This module is not recommended for beginners at this time.',
        'http://www.ebay.com/itm/171907296150'),
       (NEXTVAL('part_id_seq'), 'Raspberry Pi Deluxe Breakout Kit',
        18.39, 1,
        'Raspberry Pi Deluxe Breakout Kit',
        'Viaboot''s Understanding the GPIO Project Guide - Updated and Expanded in August 2016\nRaspberry Pi GPIO Breakout Set for all 40-pin Raspberry Pi Models: A+,
        B +, 2B and 3B\n830 Point Solderless Breadboard with 65 piece jumper set\nIncludes LED''s, Resistors, Capacitors, Transistors, Switches and more\nLearn to interact with the GPIO through Python and Scratch',
        'https://www.amazon.com/gp/product/B017C54VZA/ref=od_aui_detailpages00?ie=UTF8&psc=1'),
       (NEXTVAL('part_id_seq'), '20PCS 2 Position SPDT Mini Vertical Slide Switch',
        .99, 1,
        '20PCS 3 Pin SS12D00G3 2 Position SPDT 1P2T PCB Panel Mini Vertical Slide Switch',
        'Product Name  :   Slide Switch\n Model  :   SS-12D00G3\n Type  :   1 Pole 2 Throw\n Terminal Quantity   :  3 Pcs\n Working Power :    0.5A 50V DC\n Contact Resistance  :   30mΩ Max\n Insulation Resistance  :   100mΩ Min at 500V DC\n Withstand Voltage  :   AC 500V for 1 min\n Terminal Length  :   3mm/ 0.12in\n Pin Pitch  :   2.54mm / 1in\n Main Body Size(not include Pins & Knob)   :  8 x 4 x 3.8mm/ 0.31in x 0.16in x 0.15in(L*W*H)\n Switch Total Size  :   8 x 4 x 10mm/ 0.31in x 0.16in x 0.39in(L*W*H)\n Knob Size  :   1.5 x 1.5 x 3mm/ 0.06in x 0.06in x 0.12in(L*W*H)\n Material(External) :    Plastic, Metal\n Main Color   :  Silver Tone, Black\n',
        'https://www.ebay.com/itm/20PCS-3-Pin-SS12D00G3-2-Position-SPDT-1P2T-PCB-Panel-Mini-Vertical-Slide-Switch/311654835782?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649'),
       (NEXTVAL('part_id_seq'), '22AWG 5 color Wire',
        15.78, 1,
        '40m 22AWG 5 color Mix box 1 package Electrical Wire Line Airline Copper PCB Wire',
        'Two box packaging Color:\n Box 1-Red/Green/Blue/Yellow/Black\n Length: each roll 8 meters / total 40 meters\n Type:UL-1007\n External Material :PVC\n Condition:100% brand new never used\n Type: 22AWG\n PVC insulation, Tinned copper conductor\n Insulation Nom. Dia.: 1..6+/-0.1mm\n Maximum Conductor Resistance: 59.4 ohm/km. (at 20 ℃)\n Rated temperature: 80℃\n Rated voltage: 300V\n Passes UL VW-1 & CSA FT1 vertical flame test.\n Application: Internal wiring in electric & electric equipment.\n RoHS compliant',
        'https://www.ebay.com/itm/40m-22AWG-5-color-Mix-box-1-package-Electrical-Wire-Line-Airline-Copper-PCB-Wire/162205043599?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649'),
       (NEXTVAL('part_id_seq'), '100Pcs Push Button Switch',
        1.27, 1,
        '100Pcs Momentary Panel PCB Tactile Tact Push Button Switch 4Pin 6x6x4.5mm TS',
        'Product Name : Tact Switch;Contact Type : Momentary Contact\n Dimension : 6 x 6 x 4.5mm / 0.24in x 0.24n x 0.18in (L*W*H);Button Dia. : 3mm/ 0.12in\n Pin Pitch : 5 x 6mm / 0.2in x 0.24in (L*W);Pin Length : 5mm / 0.2in\n Material : Plastic, Metal, Electric Parts;Color : Black, Silver Tone\n Net Weight : 29g;\n Descriptions: Feature momentary contact, 4 pins, round black push button, through hole mounting, 6 x 6 x 4.5mm size, etc.\n Used in the fields of electronic products, household appliances and more.\n High precision mechanism design offers acute operation and long service life.\n Package Content : 100 x Tact Switches\n Note:Light shooting and different displays may cause the color of the item in the picture a little different from the real thing. The measurement allowed error is +/- 1-3cm',
        'https://www.ebay.com/itm/100Pcs-Momentary-Panel-PCB-Tactile-Tact-Push-Button-Switch-4Pin-6x6x4-5mm-TS/172040053810?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649'),
       (NEXTVAL('part_id_seq'), 'GPIO Pin Reference Board',
        1.97, 1,
        'GPIO Pin Reference Board For Raspberry Pi 2 Model B & Raspberry Pi B+',
        'Compatible with Raspberry Pi 2 Model B & Raspberry Pi B+\n Material: PCB\n With marked you can easily distinguish all leads of GPIO\n Dimensions: 5.3 cm x 1 cm x 0.1 cm ',
        'https://www.banggood.com/GPIO-Pin-Reference-Board-For-Raspberry-Pi-2-Model-B-Raspberry-Pi-B-p-974758.html?utm_design=41&utm_source=emarsys&utm_medium=Neworder171109&utm_campaign=trigger-emarsys&utm_content=winna&sc_src=email_2675773&sc_eh=f829836f87d6a76b1&sc_llid=6610146&sc_lid=105229698&sc_uid=cEgURK1ooI&cur_warehouse=CN'),
       (NEXTVAL('part_id_seq'), 'Network Adapter Module',
        10.44, 1,
        'Enc28j60 Network Adapter Module For Raspberry Pi Zero',
        '1. Install the NIC module into the raspberry Pi.\n 2. Connect the network cable to ensure that your router supports DHCP and works well.\n 3.Burn the Raspbian image to TF card.\n 4. Edit the /boot/config.txt file by your favorite editor such as ''Nano'' or ''vim.tiny'', and add the following parameter: \n dtoverlay=enc28j60\n Then save the exit and reboot the raspberry Pi.',
        'https://www.banggood.com/Enc28j60-Network-Adapter-Module-For-Raspberry-Pi-Zero-p-1252558.html?utm_design=41&utm_source=emarsys&utm_medium=Neworder171109&utm_campaign=trigger-emarsys&utm_content=winna&sc_src=email_2675773&sc_eh=f829836f87d6a76b1&sc_llid=6610146&sc_lid=105229698&sc_uid=cEgURK1ooI&cur_warehouse=CN'),
       (NEXTVAL('part_id_seq'), 'Cluster HAT v2',
        55.93, 1,
        'Cluster HAT v2 for the Raspberry Pi',
        'The Cluster HAT (Hardware Attached on Top) interfaces a (Controller) Raspberry Pi A+/B+/2/3 with (up to) 4 Raspberry Pi Zeros (1.1/1.2 or W) configured to use USB Gadget mode is an ideal tool for teaching or testing small scale clusters.\n \n USB Gadget Mode: Ethernet and Serial Console.\n Onboard 4 port USB 2.0 hub.\n Raspberry Pi Zeros powered via Controller Pi GPIO\n Individual Raspberry Pi Zero power controlled via Controller Pi GPIO (I2C).\n Connector for Controller Serial Console (our USB Serial Adaptor or a Sparkfun FTDI Basic).\n Controller Pi can be rebooted without interrupting power to Pi Zeros (network recovers on boot).\n The standard ClusterHAT package contains (Power supply/network cable/Raspberry Pi 3/Zeros not included):\n \n 1x ClusterHAT PCB*\n 4x 12mm M2.5 standoff\n 8x 6mm M2.5 screw\n 4x stick on foot\n USB Cable*',
        'https://www.ebay.com/itm/Cluster-HAT-for-the-Raspberry-Pi-/201659118283?hash=item2ef3d1f2cb:g:rTsAAOSwKfVXH~rK'),
       (NEXTVAL('part_id_seq'), '75 Watt - Soldering Iron Station',
        69.80, 1,
        'X-Tronic Model #3020-XTS-ST - 75 Watt - Soldering Iron Station with 10 Min Sleep Function, Auto Cool Down, C/F Switch, Ergonomic Soldering Iron Plus More (Soldering Station-Complete with 5 Extra Tips)',
        '1 - 75 Watt Soldering Iron Station (60 Watts for Soldering Iron/15 Watts for Soldering Iron Mother Board)\n 1 - 60 Watt Soldering Iron with a Temperature Range of 392°F ~ 896°F/200°C ~ 480°C\n 5 - Extra Sizes/Styles of Soldering Tips\n 1 - Solder Roll Holder on the Side of the Unit (Roll of Solder is Not Included)\n 1 - Spring Style Soldering Iron Holder\n 1 - Brass Sponge Tip Cleaner with a supply of Cleaning Flux at the bottom of the tin',
        'https://www.amazon.com/gp/product/B079VVHPPS/ref=oh_aui_detailpage_o01_s01?ie=UTF8&psc=1'),
       (NEXTVAL('part_id_seq'), 'Helping Hand Station with Magnifying Glass',
        67.99, 1,
        'RC Logger Helping Hand Station with Magnifying Glass Third Hand LED Lamp Solder Holder Heavy Base and Sponge for Soldering Work Hobby, Repair, Model Games, Workshop and Assembly, Gift Idea',
        'Mains power supply 100 - 240 V/AC, 5 V/DC, 600 mA\n 16 LEDs lighting\n Environment conditions from -20 to +40 °C\n Stand dimensions (W x H) 178 x 178 mm\n Gooseneck length (lens) 265 mm\n Gooseneck length (third hand) 250 mm\n Spindle holder (Ø x L) 10 x 82 mm / 19 x 82 mm\n 290 mm height\n Weight: 1.3 kg',
        'https://www.amazon.com/gp/product/B079VVHPPS/ref=oh_aui_detailpage_o01_s01?ie=UTF8&psc=1'),
       (NEXTVAL('part_id_seq'), 'ESP8266 ESP-01',
        1.96, 1,
        'ESP8266 ESP-01 Serial WIFI Wireless Transceiver Module Send Receive LWIP AP+STA',
        '802.11 b/g/n\n\n Wi-Fi Direct (P2P), soft-AP\n Integrated TCP/IP protocol stack\n Integrated TR switch, balun, LNA, power amplifier and matching network\n Integrated PLLs, regulators, DCXO and power management units\n +19.5dBm output power in 802.11b mode\n Power down leakage current of <10uA\n Integrated low power 32-bit CPU could be used as application processor\n SDIO 1.1/2.0, SPI, UART\n STBC, 1×1 MIMO, 2×1 MIMO\n A-MPDU & A-MSDU aggregation & 0.4ms guard interval\n Wake up and transmit packets in < 2ms\n Standby power consumption of < 1.0mW (DTIM3)',
        'https://www.ebay.com/itm/ESP8266-ESP-01-Serial-WIFI-Wireless-Transceiver-Module-Send-Receive-LWIP-AP-STA/201501780189?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649'),
       (NEXTVAL('part_id_seq'), 'SanDisk® microSDHCTM 8GB Memory Card',
        6.07, 3,
        'SanDisk® microSDHCTM 8GB Memory Card',
        'microSD mobile memory cards are the ideal companion for multimedia phones because they plug right inside the phone providing immediate expansion of memory storage needed for carrying more music, video, photos, games, and mobile software applications in the latest generation of phones',
        'https://www.amazon.com/gp/product/B0012Y2LLE/ref=oh_aui_detailpage_o05_s00?ie=UTF8&psc=1'),
       (NEXTVAL('part_id_seq'), 'Sandisk Ultra 32GB Micro Card',
        6.07, 2,
        'Sandisk Ultra 32GB Micro SDHC UHS-I Card with Adapter - 98MB/s U1 A1 - SDSQUAR-032G-GN6MA',
        'UHS Speed Class U1 and Speed Class 10 for Full HD video recording and playback (Full HD (1920x1080) video support may vary based upon host device, file attributes, and other factors.)',
        'https://www.amazon.com/gp/product/B073JWXGNT/ref=oh_aui_detailpage_o04_s00?ie=UTF8&psc=1'),
       (NEXTVAL('part_id_seq'), '3-Pack Micro USB Cable',
        6.99, 1,
        '3-Pack Micro USB Cable Type A to Micro B Data Sync Charger Adapter Cable- 3 ft.',
        'Universal, For Samsung Galaxy Note 3, For Samsung Galaxy Note 4, For Samsung Galaxy S4, For Samsung Galaxy S5, For Samsung Galaxy S6, For Samsung Galaxy S7',
        'https://www.ebay.com/itm/3-Pack-Micro-USB-Cable-Type-A-to-Micro-B-Data-Sync-Charger-Adapter-Cable-3-ft/331996398800?ssPageName=STRK%3AMEBIDX%3AIT&var=541038881367&_trksid=p2057872.m2749.l2649'),
       (NEXTVAL('part_id_seq'), 'USB 2.0 3FT Cable Black',
        2.38, 1,
        'USB 2.0 A Male to A Male 3FT Cable Black',
        'Connectors: 4-pin USB 2.0 Type A – male',
        'https://www.ebay.com/itm/USB-2-0-A-Male-to-A-Male-3FT-Cable-Black/121923141739?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649'),
       (NEXTVAL('part_id_seq'), '9V 1A Power Adapter',
        5.69, 1,
        'ZJchao 9V 1A Power Adapter for Arduino (2-Flat-Pin Plug / 100CM Cable)',
        'Input: 100~240V, 50/60Hz\n Output: 9V, 1A\n 2-flat-pin plug\n Connector size: 5.5 x 2.1mm\n Cable Length: 100cm',
        'https://www.amazon.com/gp/product/B00CP1QLSC/ref=oh_aui_detailpage_o02_s00?ie=UTF8&psc=1'),
       (NEXTVAL('part_id_seq'), 'Desoldering Wick, Sucker & Braid',
        6.99, 1,
        'OMorc Desoldering Wick, Solder Sucker & Solder Braid',
        'Solder Wick Braid. The desoldering wick is 2.5mm wide and 1.5m in length. Weight: 0.4oz. With low residue design, this solder braid will help clean spare solder on the pin away to avoid short circuit, especially in small, hard to reach areas.',
        'https://www.amazon.com/gp/product/B01I14V4X8/ref=oh_aui_detailpage_o03_s00?ie=UTF8&psc=1'),
       (NEXTVAL('part_id_seq'), 'Lead Free Solder Wire',
        10.99, 1,
        'Mudder Lead Free Solder Wire Sn99 Ag0.3 Cu0.7 with Rosin Core for Electrical Soldering 0.22lbs (0.6 mm)',
        'Lead-free solder wire: lead-free solder wire with rosin core; It weighs 100 g/ 0.22 lb; The size of solder wire roll is 5.4 x 5.4 x 2.8 cm/ 2.1 x 2.1 x 1.1 inches',
        'https://www.amazon.com/gp/product/B01B61TWGY/ref=oh_aui_detailpage_o03_s00?ie=UTF8&psc=1'),
       (NEXTVAL('part_id_seq'), '5V 2.5A AC Adapter',
        6.13, 1,
        '5V 2.5A AC Adapter Micro USB For Raspberry Pi 3 Power Supply Adapter Charger',
        'Output: DC 5V 2.5A (2500mA)\n Input Voltage: 100~240VAC 50/60Hz, Worldwide Use\n DC Connector: Micro usb\n Cable length: 4FT (110 cm)\n Safe standard: FCC，CE, RoSH\n Brand New Ac Power Adapter Charger\n Short-circuit Protection, Over Voltage Protection, Over Heat Protection',
        'https://www.ebay.com/itm/272388057169?autorefresh=true'),
       (NEXTVAL('part_id_seq'), '5X Breadboard Adapter for ESP8266 ESP-01',
        4.33, 1,
        '5X Breadboard Adapter PCB for ESP8266 ESP-01 ESP-01S Breakout Serial Wifi Module',
        'This is a breadboard adapter for the popular ESP-01 ESP-01S\n As ESP-01/01S Pin arrangements are not breadboard friendly and are not labeled, which makes it little inconvenient for rapid prototyping.This breadboard adapter will help you to make prototyping with esp-01/01S module much more easier.\nThis breakout conveniently offers clear pinout silkprint on top and will nicely fit your prefered breadboard.\nLast but not least, we added a 0.1µF decoupling capacitor so the ESP-01 will always run smoothly and without a hitch.',
        'https://www.ebay.com/itm/5X-Breadboard-Adapter-PCB-for-ESP8266-ESP-01-ESP-01S-Breakout-Serial-Wifi-Module/282188368575?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2060353.m2749.l2649'),
       (NEXTVAL('part_id_seq'), 'USB to ESP-01 Adapter',
        10.99, 1,
        'ESP8266 Wireless WiFi Module Wi-Fi CH340G, UART PORG, 4.5-5.5V, 115200 Baud Rate',
        'ESP8266 Wireless WiFi Module Wi-Fi CH340G, UART PORG, 4.5-5.5V, 115200 Baud Rate',
        'https://www.amazon.com/gp/product/B07Q17XJ36/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1'),
       (NEXTVAL('part_id_seq'), 'ELEGOO 32 Pcs Double Sided PCB Board',
        12.99, 1,
        'ELEGOO 32 Pcs Double Sided PCB Board Prototype Kit for DIY Soldering with 5 Sizes Compatible with Arduino Kits',
        'ELEGOO 32 Pcs Double Sided PCB Board Prototype Kit for DIY Soldering with 5 Sizes Compatible with Arduino Kits',
        'https://www.amazon.com/gp/product/B072Z7Y19F/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1'),
       (NEXTVAL('part_id_seq'), '3v Relay Board Power Switch',
        14.99, 1,
        '3v Relay Board Power Switch Relay Module 1 Channel Optocoupler',
        '3v Relay Board Power Switch Relay Module 1 Channel Optocoupler',
        'https://www.amazon.com/gp/product/B07ZM84BVX/ref=ox_sc_act_title_2?smid=A19Q8UDLC379P5&psc=1'),
       (NEXTVAL('part_id_seq'), '100uF Aluminum Electrolytic Capacitors',
        6.99, 1,
        '100uF 25V 6.3X11 +/-20% -40 to +105°C 50 PCS Aluminum Electrolytic Capacitors',
        '100uF 25V 6.3X11 +/-20% -40 to +105°C 50 PCS Aluminum Electrolytic Capacitors',
        'https://www.amazon.com/gp/product/B076GZX6F5/ref=ox_sc_act_image_1?smid=A3VYBV9SG5O81M&psc=1'),
       (NEXTVAL('part_id_seq'), 'AMS1117 Voltage Regulator 3.3V 1A',
        5.99, 1,
        '(Pack of 10) AMS1117 Voltage Regulator 3.3V 1A SOT-223 AMS1117-3.3V',
        '(Pack of 10) AMS1117 Voltage Regulator 3.3V 1A SOT-223 AMS1117-3.3V',
        'https://www.amazon.com/gp/product/B07MVWCXQK/ref=ewc_pr_img_2?smid=A1G4TRJSF885ET&psc=1'),
       (NEXTVAL('part_id_seq'), 'HiLetgo ESP-WROOM-32 Development Board',
        10.99, 1,
        'HiLetgo ESP-WROOM-32 ESP32 ESP-32S Development Board 2.4GHz Dual-Mode WiFi + Bluetooth Dual Cores Microcontroller',
        'HiLetgo ESP-WROOM-32 ESP32 ESP-32S Development Board 2.4GHz Dual-Mode WiFi + Bluetooth Dual Cores Microcontroller Processor Integrated with Antenna RF AMP Filter AP STA for Arduino IDE',
        'https://www.amazon.com/HiLetgo-ESP-WROOM-32-Development-Microcontroller-Integrated/dp/B0718T232Z/ref=sr_1_4?crid=WBCW55Q3SS6M&dchild=1&keywords=esp32&qid=1613740972&sprefix=esp32%2Caps%2C236&sr=8-4'),
       (NEXTVAL('part_id_seq'), 'ESP8266 5V Wifi Relay',
        1.85, 1,
        'ESP8266 5V Wifi Relay Module Remote Control Switch',
        'ESP8266 5V Wifi Relay Module Remote Control Switch',
        'https://www.aliexpress.com/snapshot/0.html?orderId=8126858973847577&productId=32964135411&edm_click_module=order_detail&tracelog=rowan&rowan_id1=buyerPayOnlineSuccessToBuyerV2_1_en_US_2021-03-01&rowan_msg_id=7577812685897383$2e75de606cd9424c90c4a2e390914ece&ck=in_edm_other'),
       (NEXTVAL('part_id_seq'), 'HiLetgo ESP8266 5V WIFI Relay Module',
        8.99, 1,
        'Onboard Relay:5V,10A/250V AC 10A/30V DC relay',
        'Onboard Relay:5V,10A/250V AC 10A/30V DC relay',
        'https://www.amazon.com/gp/product/B071LMSLRW/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1'),
       (NEXTVAL('part_id_seq'), 'HiLetgo 1PC ESP8266 NodeMCU CP2102 ESP-12E',
        6.49, 1,
        'HiLetgo 1PC ESP8266 NodeMCU CP2102 ESP-12E Internet WiFi Development Board Open Source Serial Wireless Module',
        'HiLetgo 1PC ESP8266 NodeMCU CP2102 ESP-12E Internet WiFi Development Board Open Source Serial Wireless Module',
        'https://www.amazon.com/HiLetgo-Internet-Development-Wireless-Micropython/dp/B010O1G1ES/ref=sr_1_1_sspa?dchild=1&keywords=ESP8266%2BESP-12E&qid=1613101616&sr=8-1-spons&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyTDJIWVAyMzJCTFU4JmVuY3J5cHRlZElkPUExMDA1NzY0MjBQOVhWQ0M0VzZWQSZlbmNyeXB0ZWRBZElkPUEwNTYyNjkzMU5WTEI1SjdJUTlDJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ&th=1'),
       (NEXTVAL('part_id_seq'), 'LIBO Electric Magnetic Lock',
        16.89, 1,
        '60KG/130lbs Access Control Electronic Metal Door Lock DC12V Fail Safe NC Type for Security System Single Door',
        '60KG/130lbs Access Control Electronic Metal Door Lock DC12V Fail Safe NC Type for Security System Single Door',
        'https://www.amazon.com/gp/product/B07DPQ5VZ9/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1'),
       (NEXTVAL('part_id_seq'), 'UHPPOTE Power Supply 110-240VAC to 12VDC',
        16.70, 1,
        'UHPPOTE Power Supply 110-240VAC to 12VDC for Door Access Control System & Intercom Camera',
        'UHPPOTE Power Supply 110-240VAC to 12VDC for Door Access Control System & Intercom Camera',
        'https://www.amazon.com/gp/product/B00V55INJE/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1')
;

insert into PART_IMAGES(ID, PART_ID, MEDIA_TYPE, CONTENT)
values (NEXTVAL('part_images_id_seq'), 1,  'image/jpg', FILE_READ('${imgdir}/41LFsc4PtcL._SY450_.jpg')),
       (NEXTVAL('part_images_id_seq'), 1,  'image/jpg', FILE_READ('${imgdir}/516FEDRT9oL._SY450_.jpg')),
       (NEXTVAL('part_images_id_seq'), 2,  'image/jpg', FILE_READ('${imgdir}/Solderless-bb.jpg')),
       (NEXTVAL('part_images_id_seq'), 3,  'image/jpg', FILE_READ('${imgdir}/ospi.jpg')),
       (NEXTVAL('part_images_id_seq'), 4,  'image/png', FILE_READ('${imgdir}/ultrasonic-sensor1.png')),
       (NEXTVAL('part_images_id_seq'), 4,  'image/png', FILE_READ('${imgdir}/ultrasonic-sensor2.png')),
       (NEXTVAL('part_images_id_seq'), 5,  'image/jpg', FILE_READ('${imgdir}/usb-otg-micro.jpg')),
       (NEXTVAL('part_images_id_seq'), 6,  'image/jpg', FILE_READ('${imgdir}/BB-ADTR1.jpg')),
       (NEXTVAL('part_images_id_seq'), 6,  'image/jpg', FILE_READ('${imgdir}/BB-ADTR2.jpg')),
       (NEXTVAL('part_images_id_seq'), 7,  'image/jpg', FILE_READ('${imgdir}/temp-humidity1.jpg')),
       (NEXTVAL('part_images_id_seq'), 7,  'image/jpg', FILE_READ('${imgdir}/temp-humidity2.jpg')),
       (NEXTVAL('part_images_id_seq'), 8,  'image/png', FILE_READ('${imgdir}/bb-power-supply.png')),
       (NEXTVAL('part_images_id_seq'), 9,  'image/jpg', FILE_READ('${imgdir}/esp8266-dev-board.jpg')),
       (NEXTVAL('part_images_id_seq'), 9,  'image/jpg', FILE_READ('${imgdir}/esp8266-dev-board-example.jpg')),
       (NEXTVAL('part_images_id_seq'), 9,  'image/png', FILE_READ('${imgdir}/esp8266-dev-board2.png')),
       (NEXTVAL('part_images_id_seq'), 10, 'image/jpg', FILE_READ('${imgdir}/step-down-converter.jpg')),
       (NEXTVAL('part_images_id_seq'), 11, 'image/png', FILE_READ('${imgdir}/mini-hdmi-male-female.png')),
       (NEXTVAL('part_images_id_seq'), 12, 'image/jpg', FILE_READ('${imgdir}/edimax-wifi.jpg')),
       (NEXTVAL('part_images_id_seq'), 13, 'image/jpg', FILE_READ('${imgdir}/magnifying-glass.jpg')),
       (NEXTVAL('part_images_id_seq'), 14, 'image/jpg', FILE_READ('${imgdir}/db-sided-perf-board.jpg')),
       (NEXTVAL('part_images_id_seq'), 15, 'image/jpg', FILE_READ('${imgdir}/2-level-logic-converter.jpg')),
       (NEXTVAL('part_images_id_seq'), 16, 'image/jpg', FILE_READ('${imgdir}/resistor-asst.jpg')),
       (NEXTVAL('part_images_id_seq'), 17, 'image/jpg', FILE_READ('${imgdir}/pnp.jpg')),
       (NEXTVAL('part_images_id_seq'), 18, 'image/jpg', FILE_READ('${imgdir}/npn.jpg')),
       (NEXTVAL('part_images_id_seq'), 19, 'image/jpg', FILE_READ('${imgdir}/oled.jpg')),
       (NEXTVAL('part_images_id_seq'), 20, 'image/jpg', FILE_READ('${imgdir}/potentiometer.jpg')),
       (NEXTVAL('part_images_id_seq'), 21, 'image/jpg', FILE_READ('${imgdir}/mag-sensor.jpg')),
       (NEXTVAL('part_images_id_seq'), 22, 'image/jpg', FILE_READ('${imgdir}/s-l400.jpg')),
       (NEXTVAL('part_images_id_seq'), 23, 'image/jpg', FILE_READ('${imgdir}/s-l64.jpg')),
       (NEXTVAL('part_images_id_seq'), 24, 'image/jpg', FILE_READ('${imgdir}/solar-panel.jpg')),
       (NEXTVAL('part_images_id_seq'), 25, 'image/jpg', FILE_READ('${imgdir}/camera.jpg')),
       (NEXTVAL('part_images_id_seq'), 26, 'image/jpg', FILE_READ('${imgdir}/batter-compartment.jpg')),
       (NEXTVAL('part_images_id_seq'), 27, 'image/jpg', FILE_READ('${imgdir}/batteries.jpg')),
       (NEXTVAL('part_images_id_seq'), 28, 'image/jpg', FILE_READ('${imgdir}/sku_94518_1.jpg')),
       (NEXTVAL('part_images_id_seq'), 28, 'image/jpg', FILE_READ('${imgdir}/sku_94518_2.jpg')),
       (NEXTVAL('part_images_id_seq'), 28, 'image/jpg', FILE_READ('${imgdir}/sku_94518_3.jpg')),
       (NEXTVAL('part_images_id_seq'), 28, 'image/jpg', FILE_READ('${imgdir}/sku_94518_4.jpg')),
       (NEXTVAL('part_images_id_seq'), 29, 'image/jpg', FILE_READ('${imgdir}/micro-usb-male.jpg')),
       (NEXTVAL('part_images_id_seq'), 30, 'image/jpg', FILE_READ('${imgdir}/buck-step-down-converter1.jpg')),
       (NEXTVAL('part_images_id_seq'), 30, 'image/jpg', FILE_READ('${imgdir}/buck-step-down-converter2.jpg')),
       (NEXTVAL('part_images_id_seq'), 31, 'image/png', FILE_READ('${imgdir}/FTDI-USB-to-TTL.png')),
       (NEXTVAL('part_images_id_seq'), 32, 'image/png', FILE_READ('${imgdir}/esp8266-1.png')),
       (NEXTVAL('part_images_id_seq'), 33, 'image/jpg', FILE_READ('${imgdir}/71SDR3Qup9L._SL1000_.jpg')),
       (NEXTVAL('part_images_id_seq'), 34, 'image/jpg', FILE_READ('${imgdir}/1P2T-vertical-slide-switch.jpg')),
       (NEXTVAL('part_images_id_seq'), 35, 'image/jpg', FILE_READ('${imgdir}/wire.jpg')),
       (NEXTVAL('part_images_id_seq'), 36, 'image/jpg', FILE_READ('${imgdir}/push-button.jpg')),
       (NEXTVAL('part_images_id_seq'), 37, 'image/png', FILE_READ('${imgdir}/reference-board.png')),
       (NEXTVAL('part_images_id_seq'), 38, 'image/png', FILE_READ('${imgdir}/network-adapter.png')),
       (NEXTVAL('part_images_id_seq'), 39, 'image/png', FILE_READ('${imgdir}/pi-hat-cluster-1.png')),
       (NEXTVAL('part_images_id_seq'), 39, 'image/png', FILE_READ('${imgdir}/pi-hat-cluster-2.png')),
       (NEXTVAL('part_images_id_seq'), 39, 'image/png', FILE_READ('${imgdir}/pi-hat-cluster-3.png')),
       (NEXTVAL('part_images_id_seq'), 40, 'image/jpg', FILE_READ('${imgdir}/soldering-iron-station.jpg')),
       (NEXTVAL('part_images_id_seq'), 41, 'image/png', FILE_READ('${imgdir}/helping-station.png')),
       (NEXTVAL('part_images_id_seq'), 42, 'image/png', FILE_READ('${imgdir}/esp8266-esp-01.png')),
       (NEXTVAL('part_images_id_seq'), 43, 'image/png', FILE_READ('${imgdir}/sandisk-8gb.png')),
       (NEXTVAL('part_images_id_seq'), 44, 'image/png', FILE_READ('${imgdir}/sandisk-32gb.png')),
       (NEXTVAL('part_images_id_seq'), 45, 'image/png', FILE_READ('${imgdir}/3-pack-micro-usb.png')),
       (NEXTVAL('part_images_id_seq'), 46, 'image/png', FILE_READ('${imgdir}/male-2-male-usb.png')),
       (NEXTVAL('part_images_id_seq'), 47, 'image/png', FILE_READ('${imgdir}/9v-power-adapter.png')),
       (NEXTVAL('part_images_id_seq'), 48, 'image/png', FILE_READ('${imgdir}/desoldering-wick-sucker.png')),
       (NEXTVAL('part_images_id_seq'), 49, 'image/png', FILE_READ('${imgdir}/solder-wire.png')),
       (NEXTVAL('part_images_id_seq'), 50, 'image/png', FILE_READ('${imgdir}/5v-2.5a-psu.png')),
       (NEXTVAL('part_images_id_seq'), 51, 'image/png', FILE_READ('${imgdir}/bbadapterboards.png')),
       (NEXTVAL('part_images_id_seq'), 52,  'image/jpg', FILE_READ('${imgdir}/71s1KmI1AXL._AC_SL1001_.jpg')),
       (NEXTVAL('part_images_id_seq'), 52,  'image/jpg', FILE_READ('${imgdir}/61ukGjYeNFL._AC_SL1001_.jpg')),
       (NEXTVAL('part_images_id_seq'), 52,  'image/jpg', FILE_READ('${imgdir}/71tdeC64RZL._AC_SL1001_.jpg')),
       (NEXTVAL('part_images_id_seq'), 52,  'image/jpg', FILE_READ('${imgdir}/51BYHwUaOZL._AC_.jpg')),
       (NEXTVAL('part_images_id_seq'), 53,  'image/jpg', FILE_READ('${imgdir}/91H0v9bUfHL._SL1500_.jpg')),
       (NEXTVAL('part_images_id_seq'), 54,  'image/jpg', FILE_READ('${imgdir}/3vRelayBoardPowerSwitchRelayModule1ChannelOptocoupler-1.jpg')),
       (NEXTVAL('part_images_id_seq'), 54,  'image/jpg', FILE_READ('${imgdir}/3vRelayBoardPowerSwitchRelayModule1ChannelOptocoupler-2.jpg')),
       (NEXTVAL('part_images_id_seq'), 54,  'image/jpg', FILE_READ('${imgdir}/3vRelayBoardPowerSwitchRelayModule1ChannelOptocoupler-3.jpg')),
       (NEXTVAL('part_images_id_seq'), 55,  'image/jpg', FILE_READ('${imgdir}/51yu1WCpA0L._SL1000_.jpg')),
       (NEXTVAL('part_images_id_seq'), 56,  'image/jpg', FILE_READ('${imgdir}/61D6eazoGoL._SL1500_.jpg')),
       (NEXTVAL('part_images_id_seq'), 57,  'image/jpg', FILE_READ('${imgdir}/71d6+P4PUzL._AC_SL1067_.jpg')),
       (NEXTVAL('part_images_id_seq'), 57,  'image/jpg', FILE_READ('${imgdir}/61RixSStGBL._AC_SL1000_.jpg')),
       (NEXTVAL('part_images_id_seq'), 58,  'image/jpg', FILE_READ('${imgdir}/ESP8266-5V-Wifi-Relay-Module-Remote-Control-Switch_1.png')),
       (NEXTVAL('part_images_id_seq'), 58,  'image/jpg', FILE_READ('${imgdir}/ESP8266-5V-Wifi-Relay-Module-Remote-Control-Switch_2.png')),
       (NEXTVAL('part_images_id_seq'), 58,  'image/jpg', FILE_READ('${imgdir}/ESP8266-5V-Wifi-Relay-Module-Remote-Control-Switch_3.png')),
       (NEXTVAL('part_images_id_seq'), 59,  'image/jpg', FILE_READ('${imgdir}/614RIuhgSmL._AC_SL1010_.jpg')),
       (NEXTVAL('part_images_id_seq'), 59,  'image/jpg', FILE_READ('${imgdir}/61rkKFP2z9L._AC_SL1010_.jpg')),
       (NEXTVAL('part_images_id_seq'), 59,  'image/jpg', FILE_READ('${imgdir}/61pdTlk6EBL._AC_SL1010_.jpg')),
       (NEXTVAL('part_images_id_seq'), 59,  'image/jpg', FILE_READ('${imgdir}/51RU91c0z5L._AC_SL1010_.jpg')),
       (NEXTVAL('part_images_id_seq'), 60,  'image/jpg', FILE_READ('${imgdir}/HiLetgoESP8266NodeMCUCP2102ESP-12E.jpg')),
       (NEXTVAL('part_images_id_seq'), 60,  'image/jpg', FILE_READ('${imgdir}/HiLetgoESP8266NodeMCUCP2102ESP-12EPinLayout.jpg')),
       (NEXTVAL('part_images_id_seq'), 61,  'image/jpg', FILE_READ('${imgdir}/61n9-nYWFjL._AC_SL1000_.jpg')),
       (NEXTVAL('part_images_id_seq'), 61,  'image/jpg', FILE_READ('${imgdir}/61kAZEQxaML._AC_SL1000_.jpg')),
       (NEXTVAL('part_images_id_seq'), 61,  'image/jpg', FILE_READ('${imgdir}/61stRPTjBYL._AC_SL1000_.jpg')),
       (NEXTVAL('part_images_id_seq'), 61,  'image/jpg', FILE_READ('${imgdir}/61nuWBz02VL._AC_SL1000_.jpg')),
       (NEXTVAL('part_images_id_seq'), 61,  'image/jpg', FILE_READ('${imgdir}/61Umbo2UcTL._AC_SL1000_.jpg')),
       (NEXTVAL('part_images_id_seq'), 62,  'image/jpg', FILE_READ('${imgdir}/61EKZwNOokL._AC_SL1061_.jpg')),
       (NEXTVAL('part_images_id_seq'), 62,  'image/jpg', FILE_READ('${imgdir}/71LhOoLZbcL._AC_SL1278_.jpg')),
       (NEXTVAL('part_images_id_seq'), 62,  'image/jpg', FILE_READ('${imgdir}/81b+Ix-G1oL._AC_SL1500_.jpg')),
       (NEXTVAL('part_images_id_seq'), 62,  'image/jpg', FILE_READ('${imgdir}/71Br5L1Or6L._AC_SL1402_.jpg'))
;
ALTER SEQUENCE part_id_seq RESTART WITH 101 INCREMENT BY 50;
ALTER SEQUENCE part_images_id_seq RESTART WITH 120 INCREMENT BY 50;
select part_id_seq.nextval from dual;
select part_images_id_seq.nextval from dual;
